const actions = {
  ADD_USER: 'ADD_USER',
  ADD_QUESTION: 'ADD_QUESTION',
  SET_REDIRECT: 'SET_REDIRECT',
  ADD_TIME: 'ADD_TIME',
  ADD_PLAYER: 'ADD_PLAYER',
  ADD_SCORE: 'ADD_SCORE',
  ADD_RANKING: 'ADD_RANKING',
  ADD_QUESTION_NUMBER: 'ADD_QUESTION_NUMBER',
};

export default actions;
